name: guided_tour
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  chewie: ^1.13.0
  flutter:
    sdk: flutter
  video_player: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/

  